### ISSUE TITLE
Support subliminal as subtitles backend

### ISSUE THREAD

**Issue by Nikoli** [nvbn/series_list#1]
https://github.com/Diaoul/subliminal/
http://subliminal.readthedocs.org/en/latest/

Written in python, supports several providers, gives choice to download normal subtitles or for hearing-impaired. Currently it seems the most advanced and actively developed cli tool for downloading subs.

**Comment by nvbn** [comment]
Release with subliminal backend pushed to ppa.

**Comment by Nikoli** [comment]
Спасибо. А какие версии subliminal поддерживаются? 0.7.x?

**Comment by nvbn** [comment]
0.7 и 0.8(из master) должны работать.

**Comment by Nikoli** [comment]
Тогда лучше в setup.py добавить >=0.7 для subliminal.

**Comment by nvbn** [comment]
Добавил =)
